### ISSUE TITLE
[FEATURE] How to Enable Profile A/ Profile B

### ISSUE THREAD

**Issue by priyanshs** [HewlettPackard/PacketRusher#127]
**Is your feature request related to a problem? Please describe.**
Hi, PacketRusher Team, 
Thank you for such an amazing tool. I am trying to measure some network response and want that the UEs follow the SUCI-to-SUPI conversion at the core. This requires the UE to follow the same, SUPI-to-SUCI conversion. I couldn't find an option in the config.yml file. I looked at the conifguration done for [my5G-RANTester](https://github.com/my5G/my5G-RANTester) and [free5gc project](https://github.com/free5gc/free5gc). 

**Describe the solution you'd like**
Is there a way to enable this with PacketRusher? Tools like UERANSIM have this option labeled as : 
```yaml
# SUCI Protection Scheme : 0 for Null-scheme, 1 for Profile A and 2 for Profile B
protectionScheme: 1
# Home Network Public Key for protecting with SUCI Profile A
homeNetworkPublicKey: 'e421686f6fb2d70e3fa28d940494095686c3179fef53514667a6ed106b8a7d3d'
# Home Network Public Key ID for protecting with SUCI Profile A
homeNetworkPublicKeyId: 1
```

It is possible I missed something. 

Thank you
