### ISSUE TITLE
TRYING TO CREATE MULTIPLE GNBS HAVING TWO UEs INDIVIDUALLY

### ISSUE THREAD

**Issue by MusabChishti** [HewlettPackard/PacketRusher#153]
Dear Community,

I am trying to create three gNBs having its own reponsible AMF and two 5G UEs per gNB. I have already created three instances of AMF from single AMF image by the help of dockercompose mean (I have  only one AMF.yaml file).

Below is my config.yaml and dockercompose.yaml files of Packetrusher. Please check if somthing is wrong.

**config.yaml**
`gnodebs:
    controlif:
      ip: "10.33.34.20"
      port: 9487
    dataif:
      ip: "10.33.34.20"
      port: 2152
    plmnlist:
      mcc: "001"
      mnc: "01"
      tac: "000001"
    gnbid: "000008"
    slicesupportlist:
      sst: "01"
      sd: "010203"
    amfif:
      ip: "10.33.33.11"
      port: 38412

    controlif:
      ip: "10.33.34.21"
      port: 9487
    dataif:
      ip: "10.33.34.21"
      port: 2152
    plmnlist:
      mcc: "001"
      mnc: "01"
      tac: "000002"
    gnbid: "000009"
    slicesupportlist:
      sst: "01"
      sd: "010204"
    amfif:
      ip: "10.33.33.7"
      port: 38413

    controlif:
      ip: "10.33.34.22"
      port: 9487
    dataif:
      ip: "10.33.34.22"
      port: 2152
    plmnlist:
      mcc: "001"
      mnc: "01"
      tac: "000003"
    gnbid: "000010"
    slicesupportlist:
      sst: "01"
      sd: "010205"
    amfif:
      ip: "10.33.33.13"
      port: 38414

ues:
    msin: "0000000120"
    key: "00112233445566778899AABBCCDDEEFF"
    opc: "00112233445566778899AABBCCDDEEFF"
    amf: "8000"
    sqn: "00000000"
    dnn: "internet"
    routingindicator: "0000"
    hplmn:
      mcc: "999"
      mnc: "70"
    snssai:
      sst: 01
      sd: "010203"
    integrity:
      nia0: false
      nia1: true
      nia2: true
      nia3: false
    ciphering:
      nea0: true
      nea1: true
      nea2: true
      nea3: false

    msin: "0000000121"
    key: "00112233445566778899AABBCCDDEEFF"
    opc: "00112233445566778899AABBCCDDEEFF"
    amf: "8000"
    sqn: "00000000"
    dnn: "internet"
    routingindicator: "0000"
    hplmn:
      mcc: "999"
      mnc: "70"
    snssai:
      sst: 01
      sd: "010203"
    integrity:
      nia0: false
      nia1: true
      nia2: true
      nia3: false
    ciphering:
      nea0: true
      nea1: true
      nea2: true
      nea3: false

    msin: "0000000122"
    key: "00112233445566778899AABBCCDDEEFF"
    opc: "00112233445566778899AABBCCDDEEFF"
    amf: "8000"
    sqn: "00000000"
    dnn: "internet"
    routingindicator: "0000"
    hplmn:
      mcc: "999"
      mnc: "70"
    snssai:
      sst: 01
      sd: "010203"
    integrity:
      nia0: false
      nia1: true
      nia2: true
      nia3: false
    ciphering:
      nea0: true
      nea1: true
      nea2: true
      nea3: false

    msin: "0000000123"
    key: "00112233445566778899AABBCCDDEEFF"
    opc: "00112233445566778899AABBCCDDEEFF"
    amf: "8000"
    sqn: "00000000"
    dnn: "internet"
    routingindicator: "0000"
    hplmn:
      mcc: "999"
      mnc: "70"
    snssai:
      sst: 01
      sd: "010203"
    integrity:
      nia0: false
      nia1: true
      nia2: true
      nia3: false
    ciphering:
      nea0: true
      nea1: true
      nea2: true
      nea3: false

    msin: "0000000124"
    key: "00112233445566778899AABBCCDDEEFF"
    opc: "00112233445566778899AABBCCDDEEFF"
    amf: "8000"
    sqn: "00000000"
    dnn: "internet"
    routingindicator: "0000"
    hplmn:
      mcc: "999"
      mnc: "70"
    snssai:
      sst: 01
      sd: "010203"
    integrity:
      nia0: false
      nia1: true
      nia2: true
      nia3: false
    ciphering:
      nea0: true
      nea1: true
      nea2: true
      nea3: false

logs:
  level: 4`

**dockercompose.yaml**

`version: '3.8'

services:
  # gNB1
  gnb1:
    image: packetrusher:latest
    container_name: gnb1
    privileged: true
    entrypoint: /bin/bash -c "sleep infinity"
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.20
      NGAP_REMOTE_ADDR: 10.33.33.11 # AMF IP ADDR for gNB1
      GTPU_LOCAL_ADDR: 10.33.34.20
      MCC: 001
      MNC: 01
      TAC: 000001
      GNBID: "000008"
      SST_GNB: 01
      SST_UE: 01
      SD: "010203"
      MSIN: "0000000120"
      OPC: 00112233445566778899AABBCCDDEEFF
      KEY: 00112233445566778899AABBCCDDEEFF
      AMF: 8000
      SQN: 00000000
      DNN: internet
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
          ipv4_address: 10.33.34.20
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5

  # gNB2
  gnb2:
    image: packetrusher:latest
    container_name: gnb2
    privileged: true
    entrypoint: /bin/bash -c "sleep infinity"
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.21
      NGAP_REMOTE_ADDR: 10.33.33.7 # AMF IP ADDR for gNB2
      GTPU_LOCAL_ADDR: 10.33.34.21
      MCC: 001
      MNC: 01
      TAC: 000002
      GNBID: "000009"
      SST_GNB: 01
      SST_UE: 01
      SD: "010204"
      MSIN: "0000000121"
      OPC: 00112233445566778899AABBCCDDEEFF
      KEY: 00112233445566778899AABBCCDDEEFF
      AMF: 8000
      SQN: 00000000
      DNN: internet
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
          ipv4_address: 10.33.34.21
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5

  # gNB3
  gnb3:
    image: packetrusher:latest
    container_name: gnb3
    privileged: true
    entrypoint: /bin/bash -c "sleep infinity"
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.22
      NGAP_REMOTE_ADDR: 10.33.33.13 # AMF IP ADDR for gNB3
      GTPU_LOCAL_ADDR: 10.33.34.22
      MCC: 001
      MNC: 01
      TAC: 000003
      GNBID: "000010"
      SST_GNB: 01
      SST_UE: 01
      SD: "010205"
      MSIN: "0000000122"
      OPC: 00112233445566778899AABBCCDDEEFF
      KEY: 00112233445566778899AABBCCDDEEFF
      AMF: 8000
      SQN: 00000000
      DNN: internet
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
          ipv4_address: 10.33.34.22
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  privnet:
    external:
      name: docker_privnet`

By using above configurations the gNBs containers showing unhealthy and when I am running this command 

`sudo ./packetrusher multi-ue -n 6`

its showing the error mentioned below,

`musab@musab-VirtualBox:~/Desktop/PacketRusher$ sudo ./packetrusher multi-ue -n 6
[sudo] password for musab: 
ERRO[0000] Unable to resolve  in configuration for gNodeB's N3/Data IP address, make sure it is an IP address or a domain that can be resolved to an IPv4 
FATA[0000] lookup : no such host                        
musab@musab-VirtualBox:~/Desktop/PacketRusher$ 
`

**Comment by burnt-exe** [comment]
| 🛠️ **Issue:** |
|:----------------|
| The issue you're encountering seems to stem from the following key points: |


1. **Missing or incorrect IP address for `N3/Data` interfaces**:
   The error `Unable to resolve in configuration for gNodeB's N3/Data IP address` suggests that the IP address for the data interface (`GTPU_LOCAL_ADDR` or similar) is either missing or improperly configured. PacketRusher might be unable to find the correct address in your configuration.

2. **Network configuration in Docker Compose**:
   You’ve defined `privnet` as an external network but haven't provided details about its setup. If `privnet` is not properly created or its configuration does not align with your IP assignments, this could cause the containers to fail health checks or connectivity.

3. **Health checks failing for gNB containers**:
   The health checks you’ve implemented rely on a specific interface (`uetun1`) being present, which might not be created due to the above issues.


---


| 🛠️ **Resolution:** |
|:--------------------|
| Here are the steps to resolve these issues: |


### 1. **Validate IP Address Configuration**
   - Ensure the `NGAP_LOCAL_ADDR` and `GTPU_LOCAL_ADDR` match the `privnet` network’s subnet.
   - Make sure `privnet` is properly created with a matching CIDR range before launching the Docker containers:
     ```bash
     docker network create privnet --subnet=10.33.34.0/24
     ```
   - Update the `docker-compose.yaml` file if required, or validate the external network exists:
     ```yaml
     networks:
       privnet:
         external: true
     ```

---

### 2. **Debug Missing or Incorrect N3/Data IP Address**
   - Check the `packetrusher` tool’s logic for resolving `GTPU_LOCAL_ADDR`. It might expect a specific naming format or DNS resolution for container IPs.
   - Hardcode the N3/Data IP addresses to ensure correctness. For instance:
     ```yaml
     GTPU_LOCAL_ADDR: 10.33.34.20 # for gNB1
     ```

---

### 3. **Resolve the Health Check Issue**
   - The health check depends on the creation of the `uetun1` interface. This might fail due to the above configuration issues or a lack of privileges.
   - Ensure the `--cap-add=NET_ADMIN` flag is sufficient to create virtual interfaces within the container.
   - Alternatively, test the command within the container to confirm it creates `uetun1`:
     ```bash
     ip link add uetun1 type dummy
     ip link show
     ```

---

### 4. **Review `packetrusher` Command**
   - The command you used (`sudo ./packetrusher multi-ue -n 6`) specifies 6 UEs but does not clearly associate them with the gNBs. Update the command to include explicit configuration, such as:
     ```bash
     sudo ./packetrusher multi-ue -n 2 --gnbid 000008
     sudo ./packetrusher multi-ue -n 2 --gnbid 000009
     sudo ./packetrusher multi-ue -n 2 --gnbid 000010
     ```

---

### Updated `docker-compose.yaml` Example
Here is a revised version of your `docker-compose.yaml` with adjustments:
```yaml
version: '3.8'

services:
  gnb1:
    image: packetrusher:latest
    container_name: gnb1
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.20
      GTPU_LOCAL_ADDR: 10.33.34.20
      MCC: 001
      MNC: 01
      TAC: 000001
      GNBID: "000008"
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.33.34.20

  gnb2:
    image: packetrusher:latest
    container_name: gnb2
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.21
      GTPU_LOCAL_ADDR: 10.33.34.21
      MCC: 001
      MNC: 01
      TAC: 000002
      GNBID: "000009"
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.33.34.21

  gnb3:
    image: packetrusher:latest
    container_name: gnb3
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 10.33.34.22
      GTPU_LOCAL_ADDR: 10.33.34.22
      MCC: 001
      MNC: 01
      TAC: 000003
      GNBID: "000010"
      NUM_UE: 2
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.33.34.22

networks:
  privnet:
    external: true
```

---

**Final Steps**:
1. Recreate the `privnet` network:
   ```bash
   docker network rm privnet
   docker network create privnet --subnet=10.33.34.0/24
   ```
2. Start the services:
   ```bash
   docker-compose up -d
   ```
3. Verify the IP and interface configuration in the containers:
   ```bash
   docker exec -it gnb1 ip addr
   docker exec -it gnb1 ip link show
   ```

---
