### ISSUE TITLE
experiencing "Error incannot assign requested address" | multi-ue registration

### ISSUE THREAD

**Issue by HasibuzzamanFUAS** [HewlettPackard/PacketRusher#158]
Hello packetrusher team,

I am trying to implement multi-ue, so i containerized the packetrusher  in docker and up the the container to test multi-ue under same gnbs and communicate to respective upfs to check if the upf can handle huge traffics at a time or not in the network slicing scenario.

I have to deal with network slicing and testing through packetrusher. I have implemented 3 gnbs;  each gnb has a single UE, and UE can send traffic to the respective UPF till now. BUT,  **In this case(registering multi-ue), I am facing the mentioned error., would you please help to find any solutions?**

sample part docker-compose.yaml file of packetrusher-1

```
packetrusher-1:
    container_name: packetrusher-1
    image: "ghcr.io/borjis131/packetrusher:main"
    command: "--config /PacketRusher/config/packetrusher.yaml multi-ue -n 2 --tunnel-vrf -t -d"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - gnb-1.packetrusher.org
    configs:
      - source: packetrusher-1_config
        target: /PacketRusher/config/packetrusher.yaml
    privileged: true
    cap_add:
      - ALL
    depends_on:
      - amf1
```

configs file of packetrusher-1:
```
gnodeb:
  controlif:
    ip: gnb-1.packetrusher.org
    port: 38412
  dataif:
    ip: gnb-1.packetrusher.org
    port: 2152
  plmnlist:
    mcc: "262"
    mnc: "02"
    tac: "000001"
    gnbid: "000007"
  slicesupportlist:
    sst: "01"
    sd: "000001"

ue:
  msin: "1234567891"
  key: "00000000000000000000000000000000"
  opc: "00000000000000000000000000000000"
  amf: "8000"
  sqn: "00000000"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "262"
    mnc: "02"
  snssai:
    sst: 01
    sd: "000001"
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false

  msin: "1234567894"
  key: "00000000000000000000000000000000"
  opc: "00000000000000000000000000000000"
  amf: "8000"
  sqn: "00000000"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "262"
    mnc: "02"
  snssai:
    sst: 01
    sd: "000002"
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false

amfif:
  - ip: amf1.open5gs.org
    port: 38412
logs:
  level: 4

```

Logs of packetrusher-1:

```
time="2025-02-25T02:54:51Z" level=info msg="Selecting 10.33.33.8 for host amf1.open5gs.org as AMF's IP address"
time="2025-02-25T02:54:51Z" level=info msg="Selecting 10.33.33.23 for host gnb-1.packetrusher.org as gNodeB's N3/Data IP address"
time="2025-02-25T02:54:51Z" level=info msg="Selecting 10.33.33.23 for host gnb-1.packetrusher.org as gNodeB's N2/Control IP address"
time="2025-02-25T02:54:51Z" level=info msg="Loaded config at: /PacketRusher/config/packetrusher-1.yaml"
time="2025-02-25T02:54:51Z" level=info msg="PacketRusher version 1.0.1"
time="2025-02-25T02:54:51Z" level=info msg=---------------------------------------
time="2025-02-25T02:54:51Z" level=info msg="[TESTER] Starting test function: Testing registration of multiple UEs"
time="2025-02-25T02:54:51Z" level=info msg="[TESTER][UE] Number of UEs: 2"
time="2025-02-25T02:54:51Z" level=info msg="[TESTER][GNB] gNodeB control interface IP/Port: 10.33.33.23/38412~"
time="2025-02-25T02:54:51Z" level=info msg="[TESTER][GNB] gNodeB data interface IP/Port: 10.33.33.23/2152"
time="2025-02-25T02:54:51Z" level=info msg="[TESTER][AMF] AMF IP/Port: 10.33.33.8/38412"
time="2025-02-25T02:54:51Z" level=info msg=---------------------------------------
time="2025-02-25T02:54:51Z" level=info msg="[GNB] SCTP/NGAP service is running"
time="2025-02-25T02:54:51Z" level=info msg="[GNB] Initiating NG Setup Request"
time="2025-02-25T02:54:51Z" level=fatal msg="Error incannot assign requested address"
```
