### ISSUE TITLE
[FEATURE] Using FQDN/device name for the interface configuration

### ISSUE THREAD

**Issue by Borjis131** [HewlettPackard/PacketRusher#76]
I think it could be useful having the possibility to specify the gnodeb controlif (gNB N2), gnodeb dataif (gNB N3) and amfif ip (AMF N2) as FQDN/device name. Instead of using IP addresses, having a way to define a DNS name or a device name to automatically resolve the IP address.

This feature could be useful in a Docker Compose/kubernetes context where the IP addresses get automatically assigned.
```yaml
# From IP address
gnodeb:
  controlif:
    ip: "192.168.11.13"

# To FQDN
gnodeb:
  controlif:
    ip: "gnb.controlif.internal"

# To device
gnodeb:
  controlif:
    ip: "eth0"
```

Open5GS implements this approach for their configuration files.
